name: 4DSpace Research Group at UiO
title: 4DSpace Research Group
url: https://4dspace.github.io/4dspaceweb
image: /img/cover.jpeg

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: engineer
    name: Engineers
  - key: emeritus
    name: Professor Emeritus
  - key: postdoc
    name: Postdocs
  - key: researcher
    name: Researchers
  - key: phd
    name: PhD Students
  - key: master
    name: Masters Students
  - key: master-alum
    name: Past Masters Students
  - key: collab
    name: Collaborators
  - key: alum
    name: Alumni

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: '/4dspaceweb'

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /#people
  - title: Research
    link: /research.html
  - title: Research Facilities
    link: /facilities.html
  - title: Space Education
    link: /education.html
  - title: Publications
    link: /publications.html
  # - title: Code
  #   link: /code.html
